# Generated by Django 5.2.3 on 2025-07-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(default='empty', max_length=20),
        ),
    ]
